set -g mouse on
set -g status-keys vi
set -g status on
set -g mode-keys vi

unbind C-b
set -g prefix C-a

unbind %
unbind \"
bind \- split-pane -v
bind \\ split-pane -h

bind-key -n "C-h" select-pane -L
bind-key -n "C-l" select-pane -R
bind-key -n "C-j" select-pane -U
bind-key -n "C-k" select-pane -D
